### ISSUE TITLE
remove bootstrap

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql-plugin#101]
adding bootstrap is changing the JupyterLab UI, as far as I remember, we're only using it for the [connector widget](https://jupysql.ploomber.io/en/latest/api/magic-connect.html)

more details here: https://github.com/ploomber/jupysql/issues/930#issuecomment-1871308403

the connector widget only needs a few UI components, we can get rid of bootstrap and just add the necessary CSS to make it work without extra dependencies.

another option might be to re-use JupyterLab components.

@brichet do you know if JupyterLab exposes any styled components library that we can re-use? (buttons, text fields, etc)

**Comment by brichet** [comment]
Yes, you can take a look at [jupyter-ui-toolkit](https://github.com/jupyterlab-contrib/jupyter-ui-toolkit), which provides a lot of components that can be used in Jupyter ecosystem.
Jupyterlab will start using it for toolbars and button in the next minor version (`4.1.0`).

**Comment by krassowski** [comment]
Folks we (JupyterLab maintainers) are getting a number of complaints about styles being broken and it turns out to be this extension in the end. Can we help somehow?

**Comment by edublancas** [comment]
hi @krassowski, the team's availability is pretty limited right now. If there is someone who can give us a hand I'd greatly appreciate it. there's an unfinished PR here: https://github.com/ploomber/jupysql-plugin/pull/110/files

**Comment by edublancas** [comment]
@ellieko please look at this. there is an unfinished PR that might help you get started https://github.com/ploomber/jupysql-plugin/pull/110

**Comment by edublancas** [comment]
fixed by https://github.com/ploomber/jupysql-plugin/pull/118

**Comment by edublancas** [comment]
thanks, @rschroll  - you did pretty much all the work!
