### ISSUE TITLE
moving share notebook logic into a separate package

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql-plugin#103]
we want the "share notebook" logic to be present in all of our packages; hence, we want to extract it from here to make it a standalone package 

we can use this template: https://github.com/jupyterlab/extension-template

**Comment by edublancas** [comment]
Repo: https://github.com/ploomber/ploomber-extension

**Comment by neelasha23** [comment]
I dont have write access to the `ploomber-extension` repo. I have the code changes ready, and have pushed to a repo by the same name in my personal account. Once I have the permission I'll copy the files to this repo and just changed the Github urls, etc. @edublancas

**Comment by edublancas** [comment]
@neelasha23 please open another PR here, we should remove the "share notebook" logic

**Comment by neelasha23** [comment]
We need to create a conda recipe for `ploomber-extension`? @edublancas

**Comment by edublancas** [comment]
yes, please do!
