### ISSUE TITLE
Plugin breaks JupyterLab spellchecker in markdown cells

### ISSUE THREAD

**Issue by psychemedia** [ploomber/jupysql-plugin#113]
This plugin seems to break [`jupyterlab-contrib/spellchecker`](https://github.com/jupyterlab-contrib/spellchecker) in markdown cells

The spellcheck works fine in markdown cells with `jupyter labextension disable jupysql-plugin` but breaks with `jupyter labextension enable jupysql-plugin`.

**Comment by edublancas** [comment]
thanks for reporting this, we'll take a look!

**Comment by edublancas** [comment]
you haven't been nice to our team so I'm closing this. If any other user has this issue, please comment and I'll re-open

**Comment by psychemedia** [comment]
Apologies for any offence caused wheresoever and howsoever; the `'jupysql` magic is fantastically useful and heavily used in courses I run; but the breaks in spellchecker and the styling of autocomplete pop-ups caused by the `jupysql-plugin` requirement are a blocker for us.

A simple fix for end-users who just want the magic is to run `jupyter labextension disable jupysql-plugin` after installing `jupysql`, but that's another instructional step for users who don't read, or follow instructions, to omit and then wonder why things aren't working properly!
