### ISSUE TITLE
connection helper

### ISSUE THREAD

**Issue by lfunderburk** [ploomber/jupysql-plugin#16]
Idea brought forward by Catherine Devlin, need to flesh out idea in more detail

Currently users follow this workflow

```
%load_ext sql
%sql engine
```

where engine can be an in memory instance (example `%sql duckdb://`) 

Other times it can be more complex. For example https://jupysql.ploomber.io/en/latest/integrations/mysql.html or https://jupysql.ploomber.io/en/latest/integrations/mssql.html

@yafimvo proposed a solution that involved connecting via the use of ipywidgets (dev vs prod environment, different database engines, etc) 

To do:

1. Explore use cases and needs
2. Assess pain points and ways to improve
3. Find ways to ease connecting to db setups 
4. Share with community, test and iterate

**Comment by yafimvo** [comment]
@edublancas 

AC:
1. Move [jupysql-interactive-connection](https://github.com/ploomber/jupysql-interactive-connection) to jupysql-plugin repo
2. Replace `connect` command with `wizard`
3. Load existing connections if exist (.ini vs keyring)
4. Tests
5. Telemetry

Note : This implementation won't work on a classic notebook (since it's jupysql-plugin for jupyter lab).

**Comment by edublancas** [comment]
@yafimvo: do you think `connect` is clearer? (I'm starting to think so) is there any better name we can use?

**Comment by yafimvo** [comment]
> @yafimvo: do you think `connect` is clearer? (I'm starting to think so) is there any better name we can use?

In the eyes of the user who wants to establish a connection, I think `connect` is more straightforward. However, `wizard` might imply a UI with more options for the user.

Since changing the name is not complicated and it's a new feature, we can test the naming as well.

**Comment by edublancas** [comment]
let's go with `connect`
