### ISSUE TITLE
adding button for dashboard deployment

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql-plugin#17]
we're working on a cloud service to deploy notebooks as dashboards, and this package will contain an extension to deploy them with a button.

first, become familiar with building [jupyterlab extensions](https://github.com/ploomber/jupysql-plugin/tree/main/doc#jupyter-extensions). Then, implement the following

- add a toolbar button
- clicking the button should run a Python function in the backend to check for an API key ([relevant example](https://github.com/jupyterlab/extension-examples/tree/main/server-extension))
- if there is no API key, show a message with a text field so the user can paste it, it should also display a link so a person can sign up and get a key
- if an API key is stored, then clicking the button should make a request to a server, this will return a URL (to monitor deployment progress), the URL should be visible to the user
- the endpoint will also return a project-id (a string), and it should be stored in the notebook's metadata

Note that the backend services are not working yet, so implement the logic with placeholders.

**Comment by edublancas** [comment]
@tonykploomber: there's a lot of new stuff going on in this repo, so take some time to review it and understand. feel free to ask questions

**Comment by tonykploomber** [comment]
@edublancas 
When you're following the tutorial and ran the command: `jupyter labextension develop --overwrite .`

Did you see the error from the command line? 

`AttributeError: module 'hatchling.build' has no attribute 'prepare_metadata_for_build_editable'`

**Comment by edublancas** [comment]
@tonykploomber how did you fix it?

I've seen this error, I think I fixed it by downgrading from node 18 to node 16

**Comment by tonykploomber** [comment]
I just clone the project again and follow the tutorial again and resolve... I don't know what's the root cause about this yet

**Comment by edublancas** [comment]
hey @tonykploomber: this is the workflow I'm thinking. let me know what you think

```mermaid
flowchart TD
    click[Click on deploy notebook] --> api{API key stored?}
    api -- yes --> deploy{First deployment?}
    api -- no --> enter[Ask user to enter API Key]
    deploy -- yes --> confirm[Ask user to confirm deployment] -- yes --> metadata[Get project id from API and store it in the notebook's metadata]
    confirm -- no --> abort
    deploy -- no --> finish
    metadata --> finish[Deploy notebook]
    enter --> valid{valid api key?}
    valid -- no --> valid
    valid -- yes --> deploy

```

**Comment by edublancas** [comment]
> I guess the assumption of this flow is the user can see a interactive table to manage his own API Keys, and choose one of them to paste in the notebook deployment?

yes, we'll deploy a dashboard (something.ploomber.io) where they'll be able to login and manage keys

> How we gonna manage the notebook model in backend perspective? Will that be part of projects?

yes, the API will expose an endpoint to upload the notebook


> API Key status, we need to think about what if API key has an expiration date or active status in the future, how to add to this flow, and how to design our backend. For now, we can leave it but keep flexibility for this

yes, once we add expiration date to the API keys, we'll need to show errors if the API key is expired or invalid

---

One important thing that you might want to start exploring is how to write data to the current notebook.

Once the user deploys for the first time, the API will return a project ID, so each new call to "deploy notebook" uses the same project, instead of creating a new one. so you need to find a way to write to the notebook's metadata and to read from it.

notebook's schema is here: https://nbformat.readthedocs.io/en/latest/format_description.html#top-level-structure

we probably want something like this:

```json
{
  "metadata" : {
    "ploomber": {
        "project_id" : "ploomber cloud project id"
    },
    "language_info": {
        # if language_info is defined, its name field is required.
        "name" : "the programming language of the kernel",
        "version": "the version of the language",
        "codemirror_mode": "The name of the codemirror mode to use [optional]"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0,
  "cells" : [
      # list of cell dictionaries, see below
  ],
}
```

Not sure which is the best/simple approach here. if use typescript for this or implement it in python and trigger it via a server extension (read  below)

---

we also need to persist the API keys. ploomber-core already implements logic for storing API keys so I think it makes sense to re-use that logic. the way to do this is via a server extension, that allows to call python functions from the frontend via an API: https://github.com/jupyterlab/extension-examples/blob/main/server-extension/jlab_ext_example/handlers.py
