### ISSUE TITLE
Investigation - Access Notebook Metadata from jupyter extension

### ISSUE THREAD

**Issue by tonykploomber** [ploomber/jupysql-plugin#34]
Goal:

- [x] To see if the extension can retrieve the notebook metadata
- [x] To see if the extension can write the notebook metadata

===

Conclusion:
I can retrieve the notebook's metadata in the jupyter extension.
Added a button called "Experiment Notebook" which retrieves the metadata from ipynb, and I was able to write the additional metadata.

Video

https://github.com/ploomber/jupysql-plugin/assets/123580782/49ffe715-ec91-4c94-aa5e-d787f9d13741

Reference:
https://github.com/jupyterlab/jupyterlab/issues/4669#issuecomment-487413179

===

Discussion:
I think the drawback of this way is we need to modify user's notebook directly, but what if the user is using git to track the project, then any difference on the metadata will be treated as file change, this might cause some version control issue.

We might need another way to track the user's notebook and the API key. Need to think about this

**Comment by tonykploomber** [comment]
[Code is here](https://github.com/ploomber/jupysql-plugin/pull/29)

**Comment by edublancas** [comment]
this has been fixed
