### ISSUE TITLE
Issue -   AttributeError: module 'hatchling.build' has no attribute 'prepare_metadata_for_build_editable'

### ISSUE THREAD

**Issue by tonykploomber** [ploomber/jupysql-plugin#40]
Sometimes I saw the issue in `Install dependencies` in the CI:

`AttributeError: module 'hatchling.build' has no attribute 'prepare_metadata_for_build_editable'`I did see the issue on my local before, this happens sometimes on the GitHub action (not every time)Need to checkRef: https://github.com/ploomber/jupysql-plugin/actions/runs/5348188755/jobs/9697730254

**Comment by tonykploomber** [comment]
This is the original PR I saw the issue
https://github.com/ploomber/jupysql-plugin/pull/29

**Comment by edublancas** [comment]
I encountered the same a few times, and I believe it was a NodeJS version issue.

**Comment by ofek** [comment]
That's not the actual error, you would have to scroll up to see the real one https://github.com/ploomber/jupysql-plugin/actions/runs/5348188755/jobs/9697730254#step:5:65

**Comment by edublancas** [comment]
thanks for the pointer, @ofek!

@tonykploomber: this looks like a networking issue. does it always happen or does it happen intermittently?

**Comment by edublancas** [comment]
@tonykploomber can you comment what was the issue? otherwise we won't know if it comes back

**Comment by tonykploomber** [comment]
I don't see the issue from my original PR, maybe it was intermittent thing?

**Comment by tonykploomber** [comment]
Reopen the issue:
This happened in our [latest main commit](https://github.com/ploomber/jupysql-plugin/commit/86987714a6b796b56d05229e5056dbe2e49b63a0) again.

I will see if I can resolve this on my working PR

**Comment by tonykploomber** [comment]
Update:

The issue seems resolved by adding `jlpm cache clean` in nox command

Implementation:
https://github.com/ploomber/jupysql-plugin/pull/45/files#diff-f7a16a65f061822bcc73b8296f4dc837353d379d8d9cc5307982cb6941442835R32
