### ISSUE TITLE
deploy button follow ups

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql-plugin#42]
I tested the deploy notebook button and found some quirks:

if the requirements.txt is missing, an error message should pop up. currently, this error is only visible from the terminal

>  FileNotFoundError: [Errno 2] No such file or directory: '/Users/eduardo/Desktop/deleteme2/requirements.txt'

---

API key must be validated: I entered an invalid API key and still got to the "deploy notebook" screen. instead we should get an error. You can use the `users/me` endpoint, which will return the following if the API key is invalid:

```json
{
  "detail": "Could not validate API KEY"
}
```

---

the returned URL is wrong (missing trailing s in dashboard-s):

https://platform.ploomber.io/dashboard/project/job

should be:

https://platform.ploomber.io/dashboards/project/job

---

project_id not stored under a section named ploomber:

currently: metadata -> project_id
should be: metadata -> ploomber -> project_id

important: if there's already a metadata -> ploomber section, it should keep any other existing keys. you can use this: https://github.com/ploomber/ploomber/blob/7c11ac7197de89add9909e60eb2069632075ac8c/src/ploomber/env/envdict.py#L493

```
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.3"
  },
  "project_id": "twilight-wave-9025"
 },
```

**Comment by tonykploomber** [comment]
AC:
1. Check requirements.txt on deploying phase
2. Check API is valid before showing deploying button
3. Update the deploy URL
4. Revisit if project_id can be stored to `metadata -> ploomber -> project_id`
