### ISSUE TITLE
follow ups (lower priority)

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql-plugin#43]
please start working on this after: https://github.com/ploomber/jupysql-plugin/issues/42

- let's add some basic ui-tests (at least for some cases where we don't  require an valid API key)
    - user is prompted for API key if missing when clicking "deploy notebook"
    - an error message is displayed when entering an invalid API key

Currently, when the notebook starts deployment, the URL is displayed. When clicking on it, the URL is copied to the clipboard, but it'd be better to open it in a new tab directly upon clicking

Once the deployment URL shows up, the button should not show "cancel", because there is nothing to cancel (the job has been submitted already). so it should be "close" and have blue background color. same happens with re-deployment

- there's no way to re-renter API key once it fails (better to validate when entering key and clicking on Confirm so the user is only able to get past to that stage if there's a valid api key)
- improve requirements.txt message. mention that such failed is required to deploy a notebook
- add link to docs. in different parts of the flow, we can add link to relevant sections in the docs: https://docs.cloud.ploomber.io/en/latest/

**Comment by edublancas** [comment]
@tonykploomber let's now work on this one

**Comment by edublancas** [comment]
one more thing, when running `jlpm build`, i see this warning. is this something we should take care of?

```
WARNING in shared module @emotion/react
No required version specified and unable to automatically determine one. Unable to find required version for "@emotion/react" in description file (/Users/eduardo/dev/jupysql-plugin/node_modules/@emotion/styled/base/package.json). It need to be in dependencies, devDependencies or peerDependencies.

WARNING in shared module @emotion/react
No required version specified and unable to automatically determine one. Unable to find required version for "@emotion/react" in description file (/Users/eduardo/dev/jupysql-plugin/node_modules/@mui/styled-engine/GlobalStyles/package.json). It need to be in dependencies, devDependencies or peerDependencies.

WARNING in shared module @emotion/react
No required version specified and unable to automatically determine one. Unable to find required version for "@emotion/react" in description file (/Users/eduardo/dev/jupysql-plugin/node_modules/@mui/styled-engine/StyledEngineProvider/package.json). It need to be in dependencies, devDependencies or peerDependencies.
```

**Comment by tonykploomber** [comment]
Sure, will do now
AC:
1. Add basic unit tests
2. Open the new tab when the user clicks URL section
3. Modify the style & label of cancel button
4. Add link to docs

To clarify, for this one:
> there's no way to re-renter API key once it fails (better to validate when entering key and clicking on Confirm so the user is only able to get past to that stage if there's a valid api key)

We probably need the new endpoint just for validating API Key, so when the user enters the API & confirm, we can do the validation on that before actually deploying the notebook

Valid API:
Shows API Key input box -> enter valid API Key & confirm -> (backend) do the validation of that API with success -> check first time deployment...?

Invalid API:
Shows API Key input box -> enter invalid API Key & confirm -> (backend) do the validation of that API with error -> show API Key input again

We will need one more endpoint as `(backend) do the validation of that API`, is any existing one we can use or we can create an new one?

**Comment by edublancas** [comment]
> We probably need the new endpoint just for validating API Key, so when the user enters the API & confirm, we can do the validation on that before actually deploying the notebook

you can hit GET `/users/me` (no parameters). if the API key is valid, it'll return the user's info

> Shows API Key input box -> enter invalid API Key & confirm -> (backend) do the validation of that API with error -> show API Key input again

remember to show a message saying that they're API isn't valid.

**Comment by tonykploomber** [comment]
@edublancas 
For this:
> - add link to docs. in different parts of the flow, we can add link to relevant sections in the docs: https://docs.cloud.ploomber.io/en/latest/

Do you mean add the section that will redirect to [JupyterLab plugin](https://docs.cloud.ploomber.io/en/latest/dashboards/jupyterlab-plugin.html#)?

Like this:
<img width="750" alt="Screenshot 2023-07-17 at 5 29 50 PM" src="https://github.com/ploomber/jupysql-plugin/assets/123580782/4a292af3-cde1-4eb7-bc5d-a425a61ffd90">
