### ISSUE TITLE
allow switching the host for testing

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql-plugin#49]
let's allow switching the host for testing:

`export PLOOMBER_CLOUD_HOST=https://...`

this will allow us to switch to the dev environment.

also, we can enable debugging to verify that the host has been switched, and to print any relevant information:

`export PLOOMBER_DEBUG_ENABLED=true`

this can print the host once it's loaded. Jupyter has its own console (apart from the one in the browser) unsure what's the best one to use here? if Jupyter's or the browser's one

**Comment by tonykploomber** [comment]
AC:
1. Add environment variable `PLOOMBER_CLOUD_HOST` which controls the URL of the API Endpoint, I guess we should keep the default value as `"https://cloudapi-dev.ploomber.io"`?
2. Add environment variable `PLOOMBER_DEBUG_ENABLED`, it will print the current URL of the API Endpoint if it's on, I guess the default is `false`?

### Where to print

We can use in `server_app.log.info` to print, like how we log our registered jupysql-plugin module: [_load_jupyter_server_extension](https://github.com/ploomber/jupysql-plugin/blob/main/jupysql_plugin/__init__.py#L23)

I think we can still use Jupyter's own console (will see in terminal after starting `jupyter lab`)

**Comment by edublancas** [comment]
> Add environment variable PLOOMBER_CLOUD_HOST which controls the URL of the API Endpoint, I guess we should keep the default value as "https://cloudapi-dev.ploomber.io"?

no, the default should be production.

> Add environment variable PLOOMBER_DEBUG_ENABLED, it will print the current URL of the API Endpoint if it's on, I guess the default is false? 

maybe this is too much, let's skip it
