### ISSUE TITLE
Formatting SQL

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql-plugin#5]
Adding formatting for SQL cells will be very useful. I think the simplest option is to use some typescript formatter like this: https://github.com/sql-formatter-org/sql-formatter

We can add a button to format SQL cells like this extension: https://github.com/ryantam626/jupyterlab_code_formatter

**Comment by edublancas** [comment]
this looks useful (already implements formatting): https://github.com/CybercentreCanada/jupyterlab-sql-editor

**Comment by flaviomartins** [comment]
I tested the main branch and I can confirm this works. thanks for working on this @edublancas.

However, a huge problem for me is that whenever I format the SQL code in cell with this (sql-formatter) it is being highlighted as "wrong" according to sqlint which I am using for realtime feedback while writing queries.

PS: I am using jupyter-lsp and https://github.com/joe-re/sql-language-server/tree/release which in turn uses sqlint under the hood https://github.com/joe-re/sql-language-server/tree/release/packages/sqlint to highlight sqlint rule violations.

@edublancas do you think sqlint be plucked out of the sql-language-server project for this instead?

**Comment by edublancas** [comment]
does [`sqlint`](https://www.npmjs.com/package/sqlint) have a javascript API? I only see the CLI.

if so, we could add support for sqlint in a future iteration by changing this: https://github.com/ploomber/jupysql-plugin/blob/e1637009b4a88e2969d376674b4082ec9f1f6b0d/src/formatter.ts#L71

what is the error that sqlint is showing? (why is it marking the formatted SQL as invalid?)
