### ISSUE TITLE
ConnectorWidget doesn't reflect a change in a new cell

### ISSUE THREAD

**Issue by bbeat2782** [ploomber/jupysql-plugin#52]
https://github.com/ploomber/jupysql-plugin/assets/43221691/2667984a-5fbc-4c3e-b3f3-69da86ed4f1a

As demonstrated in the video, after calling the ConnectorWidget and applying a change (creating a new connection), the change is reflected on the ConnectorWidget display.

However, if I call another ConnectorWidget in another cell, the change isn't there. The change appears after I modify the widget on that particular cell(e.g. Create new connection).

**Comment by edublancas** [comment]
@yafimvo: thoughts? can this cause users issues?
