### ISSUE TITLE
add more databases to the connector widget

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql-plugin#72]
the templates are defined here: https://github.com/ploomber/jupysql-plugin/blob/2eb8f7a43cbf9a83dd9a106ccbfa286fd7edb0ed/jupysql_plugin/widgets/db_templates.py#L10

we need to add:

- Oracle
- Microsoft SQL server
- Redshift

**Comment by neelasha23** [comment]
Acceptance criteria:
1. Add entries for `Oracle`, `Microsoft SQL server`, `Redshift` in `db_templates.py`
2. Add test cases in `test_db_templates.py`
3. Changelog entry
