### ISSUE TITLE
Formatter for  typescript / javascript files

### ISSUE THREAD

**Issue by neelasha23** [ploomber/jupysql-plugin#76]
We need to add support for a formatter for typescript / javascript files similar to `black` formatter used for Python files.

**Comment by bryannho** [comment]
Would ESLint be appropriate? It supports javascript and typescript through the typescript parser option. It works on my end with standard configuration but please let me know of any specific [config options](https://eslint.org/docs/latest/use/configure/) we would need.

**Comment by edublancas** [comment]
that's fine, let's start with the standard configuration

**Comment by bryannho** [comment]
Currently I can lint with `npx eslint`, but my understanding is it should run with `pkgmt lint` and not a seperate command. Would we need to modify ploomber/pkgmt to do so?

**Comment by edublancas** [comment]
no, that's fine. we can run `npx eslint`.

just modify package.json so eslint is installed as a development dependency and document how to run the linter
