### ISSUE TITLE
create conda recipe

### ISSUE THREAD

**Issue by edublancas** [ploomber/jupysql-plugin#84]
since jupysql-plugin is now a hard dependency for jupysql, we need to create a conda recipe for jupysql-plugin.

since jupysql-plugin is not available on conda, the PR for the new jupysql is broken: https://github.com/conda-forge/jupysql-feedstock/pull/21#issuecomment-1731748251

there is some information on how to upload packages to conda here: https://github.com/search?q=repo%3Aploomber%2Fcontributing%20conda&type=code

**Comment by edublancas** [comment]
@neelasha23 lgtm. once this is in conda, please install it from there in a new environment to ensure it works correctly

**Comment by neelasha23** [comment]
Sure!
Please add a comment in the PR so that I can tick `GitHub users listed in the maintainer section have posted a comment confirming they are willing to be listed there.`
@edublancas

**Comment by edublancas** [comment]
@neelasha23 the recipe has been merged: https://github.com/conda-forge/staged-recipes/pull/24656

please do a quick test by installing jupysql-plugin from conda and checking that things work (the connection manager, the share notebook button, sql formatting, autocompletion, etc).

if all works, we can close this

**Comment by neelasha23** [comment]
Getting error for all the features:

<img width="679" alt="Screenshot 2023-12-15 at 1 23 51 AM" src="https://github.com/ploomber/jupysql-plugin/assets/29096135/42e22888-c12a-48c0-a57f-12f0c3319876">

<img width="444" alt="Screenshot 2023-12-15 at 1 23 58 AM" src="https://github.com/ploomber/jupysql-plugin/assets/29096135/6186d4e0-36aa-4e5a-bb9d-784ada890e68">

@edublancas

**Comment by neelasha23** [comment]
Only the ConnectorWidget seems to be working:

<img width="719" alt="Screenshot 2023-12-15 at 1 33 12 AM" src="https://github.com/ploomber/jupysql-plugin/assets/29096135/d6567384-d0b9-4ef4-b9a3-fd510a6e278f">

@edublancas

**Comment by edublancas** [comment]
I think the errors you're getting are because you're using JupyterLab 4, please try again with JupyterLab 4

**Comment by neelasha23** [comment]
Features are working, but I don't see the `Share Notebook` button

<img width="505" alt="Screenshot 2023-12-15 at 9 31 11 AM" src="https://github.com/ploomber/jupysql-plugin/assets/29096135/ad353a49-b6c6-41e0-a93e-56871201425f">

<img width="473" alt="Screenshot 2023-12-15 at 9 31 34 AM" src="https://github.com/ploomber/jupysql-plugin/assets/29096135/181282a4-5b00-4ac8-9a10-87d69c64980c">


<img width="900" alt="Screenshot 2023-12-15 at 9 33 43 AM" src="https://github.com/ploomber/jupysql-plugin/assets/29096135/6c8a39b7-1436-4ce2-a25f-5582e06a0458">

<img width="769" alt="Screenshot 2023-12-15 at 9 36 38 AM" src="https://github.com/ploomber/jupysql-plugin/assets/29096135/f3abedba-d395-419a-b0ec-8598a0e33d13">



@edublancas

**Comment by neelasha23** [comment]
Features are working fine:

Connector Widget:

<img width="728" alt="Screenshot 2023-12-15 at 3 08 42 PM" src="https://github.com/ploomber/jupysql-plugin/assets/29096135/976fb4ba-329a-495d-a1c5-24e4acba7390">

New connection:

<img width="692" alt="Screenshot 2023-12-15 at 3 17 36 PM" src="https://github.com/ploomber/jupysql-plugin/assets/29096135/b4b2fca7-5fc4-4152-b25d-898f8da76b2e">


SQL Formatting:

<img width="492" alt="Screenshot 2023-12-15 at 3 10 05 PM" src="https://github.com/ploomber/jupysql-plugin/assets/29096135/05999c7b-0f06-4ef1-88b7-916989d3166a">

Autocomplete:

<img width="533" alt="Screenshot 2023-12-15 at 3 11 17 PM" src="https://github.com/ploomber/jupysql-plugin/assets/29096135/88ed53e8-5e6e-4dc8-b050-b37598a4b808">


notebook share:

<img width="883" alt="Screenshot 2023-12-15 at 3 11 31 PM" src="https://github.com/ploomber/jupysql-plugin/assets/29096135/b6e7a8d3-8511-4420-8c8a-06015f0c1986">

However I see that it is asking for creating an account? Is it expected? I didn't get any prompt for API key:

<img width="1358" alt="Screenshot 2023-12-15 at 3 11 59 PM" src="https://github.com/ploomber/jupysql-plugin/assets/29096135/d0b55221-fd18-488e-9d1d-fe18cc62f21a">


@edublancas

**Comment by edublancas** [comment]
that's fine. it won't prompt you for an API key if you set one already. we can close this then
