### ISSUE TITLE
Jupyterlab4 road map

### ISSUE THREAD

**Issue by brichet** [ploomber/jupysql-plugin#89]
Hey, thanks for this great project.

Is there a road map somewhere for porting to jupyterlab4 ?
I can see some issues related to this, and a dedicated branch, but no more information.
It should be useful to track the missing feature somewhere.

Let me know if I there is another place for this kind of question.

**Comment by brichet** [comment]
Additionally, using the `jupyterlab4` branch breaks the magics on my side.

**Comment by edublancas** [comment]
please see this for more context on jupysql-plugin jupyterlab4 compatibility: https://github.com/ploomber/jupysql/issues/930

if the magic is breaking in jupyterlab 4, please open an issue in the jupysql repository and we'll tackle it! https://github.com/ploomber/jupysql

**Comment by brichet** [comment]
Thanks for your quick answer
